In [16]:
import pandas as pd
loads = pd.read_csv('./loads.csv')
timepoints = pd.read_csv('./timepoints.csv')

loads = pd.merge(timepoints, loads, left_on='timepoint_id', right_on='timepoints', how="left")
loads = loads[['LOAD_ZONE','timepoints','zone_demand_mw']]
loads.to_csv('./del.csv', index=False)
loads

       LOAD_ZONE  timepoints  zone_demand_mw
0       Nordeste           1      963.686364
1       Oriental           1     2156.870649
2         Caribe           1     2405.017792
3     Surocciden           1     1814.571039
4      Antioquia           1     1093.779740
...          ...         ...             ...
6715    Nordeste        5376     2426.441538
6716    Oriental        5376     5430.725385
6717  Surocciden        5376     4568.860000
6718      Caribe        5376     6055.528462
6719   Antioquia        5376     2753.998462

[6720 rows x 3 columns]

In [19]:
variable_capacity_factors = pd.read_csv('./variable_capacity_factors.csv')
timepoints = pd.read_csv('./timepoints.csv')

variable_capacity_factors = pd.merge(variable_capacity_factors, timepoints, on='timepoint_id', how="right")
variable_capacity_factors = variable_capacity_factors[['GENERATION_PROJECT','timepoint_id','gen_max_capacity_factor']]
variable_capacity_factors.to_csv('./del.csv', index=False)
variable_capacity_factors

       GENERATION_PROJECT  timepoint_id  gen_max_capacity_factor
0              E_GuajiraI             1                 0.842105
1             E_Jepirachi             1                 0.842105
2             S_BSLlanos4             1                 0.000000
3             S_BSLlanos5             1                 0.000000
4              S_Belmonte             1                 0.000000
...                   ...           ...                      ...
264379             H_Zeus          5376                 0.791815
264380             INSULA          5376                 0.700806
264381             PRADO4          5376                 1.000000
264382        RIOGRANDE 1          5376                 1.000000
264383         TEQUEND1-4          5376                 0.218127

[264384 rows x 3 columns]

In [ ]:
variable_capacity_factors = pd.read_csv('./variable_capacity_factors.csv')
timepoints = pd.read_csv('./timepoints.csv')

variable_capacity_factors = pd.merge(variable_capacity_factors, timepoints, on='timepoint_id', how="right")

      timepoint_id             timestamp        timeseries
0                1      2023_Q1_labor_0h     2023_Q1_labor
1                2      2023_Q1_labor_1h     2023_Q1_labor
2                3      2023_Q1_labor_2h     2023_Q1_labor
3                4      2023_Q1_labor_3h     2023_Q1_labor
4                5      2023_Q1_labor_4h     2023_Q1_labor
...            ...                   ...               ...
1339          5372  2050_Q4_holidays_19h  2050_Q4_holidays
1340          5373  2050_Q4_holidays_20h  2050_Q4_holidays
1341          5374  2050_Q4_holidays_21h  2050_Q4_holidays
1342          5375  2050_Q4_holidays_22h  2050_Q4_holidays
1343          5376  2050_Q4_holidays_23h  2050_Q4_holidays

[1344 rows x 3 columns]

In [23]:
hydro_timeseries = pd.read_csv('./hydro_timeseries.csv')
timeseries = pd.read_csv('./timeseries.csv')

hydro_timeseries = pd.merge(hydro_timeseries, timeseries, left_on='timeseries', right_on='TIMESERIES', how="right")
hydro_timeseries = hydro_timeseries[['hydro_project','timeseries','hydro_avg_flow_mw','hydro_min_flow_mw']]
hydro_timeseries.to_csv('./del.csv', index=False)
hydro_timeseries

     hydro_project        timeseries  hydro_avg_flow_mw  hydro_min_flow_mw
0            AMOYA     2023_Q1_labor          34.715834           0.005850
1          BETANIA     2023_Q1_labor          60.772539          59.299760
2           CALIMA     2023_Q1_labor          99.600199           0.006000
3           CHIVOR     2023_Q1_labor         363.904152           0.226230
4          CUCUANA     2023_Q1_labor          14.955698           0.012310
...            ...               ...                ...                ...
1787      SNMIGUEL  2050_Q4_holidays          25.583230          14.317220
1788      SOGAMOSO  2050_Q4_holidays         612.179980         118.989690
1789          URRA  2050_Q4_holidays         158.903160          76.511270
1790      ITUANGO2  2050_Q4_holidays         856.909824          69.323557
1791      ITUANGO2  2050_Q4_holidays         131.392840          10.629612

[1792 rows x 4 columns]

In [34]:
fuel_cost = pd.read_csv('./fuel_cost.csv')
years = [2023, 2025, 2030, 2035, 2040, 2045, 2050]
fuel_cost = fuel_cost[
    fuel_cost['period'].isin(years)
]
fuel_cost.to_csv('./del.csv', index=False)
print(fuel_cost)

      load_zone         fuel  period  fuel_cost
0        Caribe     GASIMPOR    2023  12.716956
1        Caribe     GASNACIO    2023   7.231772
2      Nordeste     GASNACIO    2023   4.615200
3     Antioquia     GASNACIO    2023   7.231772
4        Caribe       BIOGAS    2023   7.231772
..          ...          ...     ...        ...
471      Caribe  COMBUSTOLEO    2050   9.052301
472  Surocciden         ACPM    2050   2.225000
473      Caribe         ACPM    2050   2.115000
474   Antioquia         ACPM    2050   1.800900
475    Oriental         ACPM    2050   1.833000

[119 rows x 4 columns]